/* Generated By:JJTree: Do not edit this line. ASTVar.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package haiyan.exp;

public class CTreeVar extends SimpleNode {
  public CTreeVar(int id) {
    super(id);
  }

  public CTreeVar(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) throws ParseException {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=426077c6ee642a8a5156a09dd9f35c3d (do not edit this line) */
