/* Generated By:JJTree: Do not edit this line. ASTNumConstrant.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package haiyan.exp;

public class CTreeNumConstrant extends SimpleNode {
  public CTreeNumConstrant(int id) {
    super(id);
  }

  public CTreeNumConstrant(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) throws ParseException {
    return visitor.visit(this, data);
  }
  
  Double getValue(){
	  return Double.parseDouble(text);
  }
}
/* JavaCC - OriginalChecksum=8726cc2e28f60fbbc8ca6f304abde652 (do not edit this line) */
