/* Generated By:JJTree: Do not edit this line. ASTNullConstrant.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package haiyan.exp;

public class CTreeNullConstrant extends SimpleNode {
  public CTreeNullConstrant(int id) {
    super(id);
  }

  public CTreeNullConstrant(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) throws ParseException {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=4578e43798e2720f10237020b9b66007 (do not edit this line) */
