/* Generated By:JJTree: Do not edit this line. ASTFunShortCircuit.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package haiyan.exp;

public class CTreeFunShortCircuit extends SimpleNode {
  public CTreeFunShortCircuit(int id) {
    super(id);
  }

  public CTreeFunShortCircuit(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) throws ParseException {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=cc910b0a728ad17016fdb2f2b4e0b26f (do not edit this line) */
