/* Generated By:JJTree: Do not edit this line. ASTStrConstant.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package haiyan.exp;

public class CTreeStrConstant extends SimpleNode {
  public CTreeStrConstant(int id) {
    super(id);
  }

  public CTreeStrConstant(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) throws ParseException {
    return visitor.visit(this, data);
  }
  
  String getValue(){
	  return text;
  }
}
/* JavaCC - OriginalChecksum=8d34a0df8bee1104b234804323d1474b (do not edit this line) */
