/* Generated By:JJTree: Do not edit this line. ASTFunFixed.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package haiyan.exp;

public class CTreeFunFixed extends SimpleNode {
  public CTreeFunFixed(int id) {
    super(id);
  }

  public CTreeFunFixed(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) throws Throwable {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ac9aff5b1cb3c50795fc331782879124 (do not edit this line) */
