/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 4.1d1 */
package haiyan.exp;

public interface ParserTreeConstants
{
  public int JJTROOT = 0;
  public int JJTVOID = 1;
  public int JJTBINOP = 2;
  public int JJTFUNSHORTCIRCUIT = 3;
  public int JJTFUNFIXED = 4;
  public int JJTFUNOP = 5;
  public int JJTBOOLCONSTRANT = 6;
  public int JJTNULLCONSTRANT = 7;
  public int JJTVAR = 8;
  public int JJTNUMCONSTRANT = 9;
  public int JJTSTRCONSTANT = 10;


  public String[] jjtNodeName = {
    "Root",
    "void",
    "BinOp",
    "FunShortCircuit",
    "FunFixed",
    "FunOp",
    "BoolConstrant",
    "NullConstrant",
    "Var",
    "NumConstrant",
    "StrConstant",
  };
}
/* JavaCC - OriginalChecksum=ded3ab8daea9b00d4d83378d35685269 (do not edit this line) */
